### ISSUE TITLE
How to support empty values in flatfile/csv ?

### ISSUE THREAD

**Issue by Toilal** [EasyBatch/easybatch-framework#103]
I have this CSV file to read from : 

```
1;Test d'éligibilité;;jfmm8283  ;12/03/2015 01:00:04;;1;1;1
2;Campagne de rebond sur test Web;;jfmm8283  ;12/03/2015 01:00:04;;1;1;1
3;Parcours;;jfmm8283  ;12/03/2015 01:00:04;;1;1;1
4;Migration;;jfmm8283  ;12/03/2015 01:00:04;;1;1;1
5;Changement Mobile;;jfmm8283  ;12/03/2015 01:00:04;;1;1;1
6;Info légale;;jfmm8283  ;12/03/2015 01:00:04;;1;1;1
...
```

As you can see, there are some empty fields in the CSV.

It seems EasyBatch doesn't support this, an exception is thrown:

```
GRAVE: An exception occurred while attempting to map record [header=[number=2, source="org.apache.commons.csv.CSVParser@569dfefb", creationDate="Tue Aug 04 15:49:51 CEST 2015"], payload="CSVRecord [comment=null, mapping={id=0, label=1, closureDate=2, author=3, creationTimestamp=4, lastModified=5, current=6, freshness=7, coherence=8}, recordNumber=2, values=[1, Test d'éligibilité, , jfmm8283  , 12/03/2015 01:00:04, , 1, 1, 1]]"]
org.easybatch.core.api.RecordMappingException: Unable to convert  to type class java.util.Date for field lastModified
	at org.easybatch.core.mapper.ObjectMapper.convertValue(ObjectMapper.java:164)
	at org.easybatch.core.mapper.ObjectMapper.mapObject(ObjectMapper.java:125)
	at org.easybatch.integration.apache.common.csv.ApacheCommonCsvRecordMapper.mapRecord(ApacheCommonCsvRecordMapper.java:49)
	at org.easybatch.core.impl.EngineImpl.mapRecord(EngineImpl.java:341)
	at org.easybatch.core.impl.EngineImpl.call(EngineImpl.java:196)
	at org.easybatch.core.impl.EngineImpl.call(EngineImpl.java:50)
	at com.orange.interactions.rio.ReferenceBatch.main(ReferenceBatch.java:48)
Caused by: java.lang.IllegalArgumentException: Value to convert must not be empty
	at org.easybatch.core.util.Utils.checkArgument(Utils.java:122)
	at org.easybatch.core.converter.DateTypeConverter.convert(DateTypeConverter.java:76)
	at org.easybatch.core.converter.DateTypeConverter.convert(DateTypeConverter.java:42)
	at org.easybatch.core.mapper.ObjectMapper.convertValue(ObjectMapper.java:161)
	... 6 more
```

Is there any configuration to map those empty values to `null` instead of throwing an error ?

The issue exists with both `flatfile` and `apache-commons-csv` module.

**Comment by Toilal** [comment]
(I'm using current master)

**Comment by benas** [comment]
Empty values are not accepted indeed. As of today, the user must provide a custom `TypeConverter` that accepts null and empty values.

Actually all type converters defined in the `org/easybatch/core/converter` do not accept null nor empty values. This is a very strict constraint and probably a design issue. I should consider removing this constraint and make converters accept null and empty values by setting null if the field is an Object and the default value if the field is a primitive type.

For your use case, I also tried the `OpenCsvRecordMapper` but it seems that OpenCsv does not support empty to null neither.
The same case for spring batch, it [seems like](http://forum.spring.io/forum/spring-projects/batch/126028-reading-a-file-if-field-is-empty-setting-the-default-value) you need to provide a custom `FieldSetMapper` for this kind of requirement.

Anyway, I just looked at your PR and  added a couple of notes. It is fine to add a `emptyToNull` parameter, but I would implement it by removing the constraint from converters (as explained above). What do you think?
