### ISSUE TITLE
Error reading Json data source

### ISSUE THREAD

**Issue by benas** [EasyBatch/easybatch-framework#48]
In version 3.0.0, when I read a Json data source I get the following error:

```
Apr 21, 2015 1:26:10 PM org.easybatch.core.impl.Engine call
INFO: Initializing easy batch engine
Apr 21, 2015 1:26:10 PM org.easybatch.core.impl.Engine call
INFO: Data source: Json stream: java.io.ByteArrayInputStream@4eb754b0
Apr 21, 2015 1:26:10 PM org.easybatch.core.impl.Engine call
INFO: Strict mode: false
Apr 21, 2015 1:26:10 PM org.easybatch.core.impl.Engine call
INFO: Total records = 0
Apr 21, 2015 1:26:10 PM org.easybatch.core.impl.Engine call
INFO: easy batch engine is running...
Apr 21, 2015 1:26:10 PM org.easybatch.core.impl.Engine call
SEVERE: An exception occurred during reading next data source record, aborting execution.
javax.json.stream.JsonParsingException: Unexpected char -1 at (line no=1, column no=7, offset=6)
	at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:532)
	at org.glassfish.json.JsonTokenizer.readString(JsonTokenizer.java:189)
	at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:376)
	at org.glassfish.json.JsonParserImpl$ObjectContext.getNextEvent(JsonParserImpl.java:255)
	at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:172)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:149)
	at org.easybatch.json.JsonRecordReader.moveToNextElement(JsonRecordReader.java:217)
	at org.easybatch.json.JsonRecordReader.readNextRecord(JsonRecordReader.java:137)
	at org.easybatch.json.JsonRecordReader.readNextRecord(JsonRecordReader.java:53)
	at org.easybatch.core.impl.Engine.readRecord(Engine.java:271)
	at org.easybatch.core.impl.Engine.call(Engine.java:128)
	at org.easybatch.json.JsonIntegrationTest.test(JsonIntegrationTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Apr 21, 2015 1:26:10 PM org.easybatch.core.impl.Engine call
INFO: Shutting down easy batch engine
```

Here is a failing test:

```java
@Test
public void test() throws Exception {
    String jsonDataSource = "[{\"id\":1},{\"id\":2}]";
    EngineBuilder.aNewEngine()
            .reader(new JsonRecordReader(new ByteArrayInputStream(jsonDataSource.getBytes())))
            .build()
            .call();
}
```

**Comment by jlcanibe** [comment]
Hi Mahmoud,

Sorry for the delay, everything worked fine, this is my test´s output:

Batch Report:
	Start time = 2015-04-24 07:45:16
	End time = 2015-04-24 07:45:16
	Status = FINISHED
	Batch duration = 32ms
	Data source = XML stream: java.io.FileInputStream@bb6ab6
	Total records = 3
	Filtered records = 0 (0.0%)
	Ignored records = 0 (0.0%)
	Rejected records = 0 (0.0%)
	Error records = 0 (0.0%)
	Success records = 3 (100.0%)
	Record processing time average = 10.666667ms

Keep on with easybatch, really nice component, im trying easyrules right now.
Thank you
